services:
  web: 
    build:
      context: app
      target: builder
    ports: 
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
  # also you can run with 
  # docker run -d -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock pedyd/hamravesh-task:1.0