# Generated by Django 3.2.16 on 2022-11-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('env', models.CharField(max_length=256)),
                ('command', models.CharField(max_length=256)),
            ],
        ),
    ]
