# Generated by Django 3.2.16 on 2022-11-06 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221106_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('environment', models.CharField(max_length=1028)),
                ('command', models.CharField(max_length=1028)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 11, 6, 11, 46, 42, 566283), max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Containers',
        ),
    ]
