# Generated by Django 3.2.16 on 2022-11-06 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_container_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 11, 48, 31, 450731), max_length=256),
        ),
    ]
