# Generated by Django 3.2.16 on 2022-11-06 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_container_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 11, 52, 13, 135581, tzinfo=utc), max_length=256),
        ),
    ]
