# Generated by Django 3.2.16 on 2022-11-06 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_container_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='container_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 12, 8, 19, 576833, tzinfo=utc), max_length=256),
        ),
    ]
