# Generated by Django 3.2.16 on 2022-11-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='env',
            new_name='envs',
        ),
    ]
