# Generated by Django 3.2.16 on 2022-11-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_env_app_envs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='envs',
            new_name='environment',
        ),
    ]
