# Generated by Django 3.2.16 on 2022-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_envs_app_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='environment',
            field=models.CharField(default='{}', max_length=256),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
