# Generated by Django 3.2.16 on 2022-11-13 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_container_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=256),
        ),
    ]
